require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TblEquivalentCoursesController do

  # This should return the minimal set of attributes required to create a valid
  # TblEquivalentCourse. As you add validations to TblEquivalentCourse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "transferID" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TblEquivalentCoursesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tbl_equivalent_courses as @tbl_equivalent_courses" do
      tbl_equivalent_course = TblEquivalentCourse.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tbl_equivalent_courses).should eq([tbl_equivalent_course])
    end
  end

  describe "GET show" do
    it "assigns the requested tbl_equivalent_course as @tbl_equivalent_course" do
      tbl_equivalent_course = TblEquivalentCourse.create! valid_attributes
      get :show, {:id => tbl_equivalent_course.to_param}, valid_session
      assigns(:tbl_equivalent_course).should eq(tbl_equivalent_course)
    end
  end

  describe "GET new" do
    it "assigns a new tbl_equivalent_course as @tbl_equivalent_course" do
      get :new, {}, valid_session
      assigns(:tbl_equivalent_course).should be_a_new(TblEquivalentCourse)
    end
  end

  describe "GET edit" do
    it "assigns the requested tbl_equivalent_course as @tbl_equivalent_course" do
      tbl_equivalent_course = TblEquivalentCourse.create! valid_attributes
      get :edit, {:id => tbl_equivalent_course.to_param}, valid_session
      assigns(:tbl_equivalent_course).should eq(tbl_equivalent_course)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TblEquivalentCourse" do
        expect {
          post :create, {:tbl_equivalent_course => valid_attributes}, valid_session
        }.to change(TblEquivalentCourse, :count).by(1)
      end

      it "assigns a newly created tbl_equivalent_course as @tbl_equivalent_course" do
        post :create, {:tbl_equivalent_course => valid_attributes}, valid_session
        assigns(:tbl_equivalent_course).should be_a(TblEquivalentCourse)
        assigns(:tbl_equivalent_course).should be_persisted
      end

      it "redirects to the created tbl_equivalent_course" do
        post :create, {:tbl_equivalent_course => valid_attributes}, valid_session
        response.should redirect_to(TblEquivalentCourse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tbl_equivalent_course as @tbl_equivalent_course" do
        # Trigger the behavior that occurs when invalid params are submitted
        TblEquivalentCourse.any_instance.stub(:save).and_return(false)
        post :create, {:tbl_equivalent_course => { "transferID" => "invalid value" }}, valid_session
        assigns(:tbl_equivalent_course).should be_a_new(TblEquivalentCourse)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TblEquivalentCourse.any_instance.stub(:save).and_return(false)
        post :create, {:tbl_equivalent_course => { "transferID" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tbl_equivalent_course" do
        tbl_equivalent_course = TblEquivalentCourse.create! valid_attributes
        # Assuming there are no other tbl_equivalent_courses in the database, this
        # specifies that the TblEquivalentCourse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TblEquivalentCourse.any_instance.should_receive(:update).with({ "transferID" => "MyString" })
        put :update, {:id => tbl_equivalent_course.to_param, :tbl_equivalent_course => { "transferID" => "MyString" }}, valid_session
      end

      it "assigns the requested tbl_equivalent_course as @tbl_equivalent_course" do
        tbl_equivalent_course = TblEquivalentCourse.create! valid_attributes
        put :update, {:id => tbl_equivalent_course.to_param, :tbl_equivalent_course => valid_attributes}, valid_session
        assigns(:tbl_equivalent_course).should eq(tbl_equivalent_course)
      end

      it "redirects to the tbl_equivalent_course" do
        tbl_equivalent_course = TblEquivalentCourse.create! valid_attributes
        put :update, {:id => tbl_equivalent_course.to_param, :tbl_equivalent_course => valid_attributes}, valid_session
        response.should redirect_to(tbl_equivalent_course)
      end
    end

    describe "with invalid params" do
      it "assigns the tbl_equivalent_course as @tbl_equivalent_course" do
        tbl_equivalent_course = TblEquivalentCourse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TblEquivalentCourse.any_instance.stub(:save).and_return(false)
        put :update, {:id => tbl_equivalent_course.to_param, :tbl_equivalent_course => { "transferID" => "invalid value" }}, valid_session
        assigns(:tbl_equivalent_course).should eq(tbl_equivalent_course)
      end

      it "re-renders the 'edit' template" do
        tbl_equivalent_course = TblEquivalentCourse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TblEquivalentCourse.any_instance.stub(:save).and_return(false)
        put :update, {:id => tbl_equivalent_course.to_param, :tbl_equivalent_course => { "transferID" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tbl_equivalent_course" do
      tbl_equivalent_course = TblEquivalentCourse.create! valid_attributes
      expect {
        delete :destroy, {:id => tbl_equivalent_course.to_param}, valid_session
      }.to change(TblEquivalentCourse, :count).by(-1)
    end

    it "redirects to the tbl_equivalent_courses list" do
      tbl_equivalent_course = TblEquivalentCourse.create! valid_attributes
      delete :destroy, {:id => tbl_equivalent_course.to_param}, valid_session
      response.should redirect_to(tbl_equivalent_courses_url)
    end
  end

end
