require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TblInstitutionsController do

  # This should return the minimal set of attributes required to create a valid
  # TblInstitution. As you add validations to TblInstitution, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "institution_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TblInstitutionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tbl_institutions as @tbl_institutions" do
      tbl_institution = TblInstitution.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tbl_institutions).should eq([tbl_institution])
    end
  end

  describe "GET show" do
    it "assigns the requested tbl_institution as @tbl_institution" do
      tbl_institution = TblInstitution.create! valid_attributes
      get :show, {:id => tbl_institution.to_param}, valid_session
      assigns(:tbl_institution).should eq(tbl_institution)
    end
  end

  describe "GET new" do
    it "assigns a new tbl_institution as @tbl_institution" do
      get :new, {}, valid_session
      assigns(:tbl_institution).should be_a_new(TblInstitution)
    end
  end

  describe "GET edit" do
    it "assigns the requested tbl_institution as @tbl_institution" do
      tbl_institution = TblInstitution.create! valid_attributes
      get :edit, {:id => tbl_institution.to_param}, valid_session
      assigns(:tbl_institution).should eq(tbl_institution)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TblInstitution" do
        expect {
          post :create, {:tbl_institution => valid_attributes}, valid_session
        }.to change(TblInstitution, :count).by(1)
      end

      it "assigns a newly created tbl_institution as @tbl_institution" do
        post :create, {:tbl_institution => valid_attributes}, valid_session
        assigns(:tbl_institution).should be_a(TblInstitution)
        assigns(:tbl_institution).should be_persisted
      end

      it "redirects to the created tbl_institution" do
        post :create, {:tbl_institution => valid_attributes}, valid_session
        response.should redirect_to(TblInstitution.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tbl_institution as @tbl_institution" do
        # Trigger the behavior that occurs when invalid params are submitted
        TblInstitution.any_instance.stub(:save).and_return(false)
        post :create, {:tbl_institution => { "institution_name" => "invalid value" }}, valid_session
        assigns(:tbl_institution).should be_a_new(TblInstitution)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TblInstitution.any_instance.stub(:save).and_return(false)
        post :create, {:tbl_institution => { "institution_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tbl_institution" do
        tbl_institution = TblInstitution.create! valid_attributes
        # Assuming there are no other tbl_institutions in the database, this
        # specifies that the TblInstitution created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TblInstitution.any_instance.should_receive(:update).with({ "institution_name" => "MyString" })
        put :update, {:id => tbl_institution.to_param, :tbl_institution => { "institution_name" => "MyString" }}, valid_session
      end

      it "assigns the requested tbl_institution as @tbl_institution" do
        tbl_institution = TblInstitution.create! valid_attributes
        put :update, {:id => tbl_institution.to_param, :tbl_institution => valid_attributes}, valid_session
        assigns(:tbl_institution).should eq(tbl_institution)
      end

      it "redirects to the tbl_institution" do
        tbl_institution = TblInstitution.create! valid_attributes
        put :update, {:id => tbl_institution.to_param, :tbl_institution => valid_attributes}, valid_session
        response.should redirect_to(tbl_institution)
      end
    end

    describe "with invalid params" do
      it "assigns the tbl_institution as @tbl_institution" do
        tbl_institution = TblInstitution.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TblInstitution.any_instance.stub(:save).and_return(false)
        put :update, {:id => tbl_institution.to_param, :tbl_institution => { "institution_name" => "invalid value" }}, valid_session
        assigns(:tbl_institution).should eq(tbl_institution)
      end

      it "re-renders the 'edit' template" do
        tbl_institution = TblInstitution.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TblInstitution.any_instance.stub(:save).and_return(false)
        put :update, {:id => tbl_institution.to_param, :tbl_institution => { "institution_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tbl_institution" do
      tbl_institution = TblInstitution.create! valid_attributes
      expect {
        delete :destroy, {:id => tbl_institution.to_param}, valid_session
      }.to change(TblInstitution, :count).by(-1)
    end

    it "redirects to the tbl_institutions list" do
      tbl_institution = TblInstitution.create! valid_attributes
      delete :destroy, {:id => tbl_institution.to_param}, valid_session
      response.should redirect_to(tbl_institutions_url)
    end
  end

end
